# Generated by Django 5.2.16 on 2026-07-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('in_preparation', 'In preparation'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='awaiting_payment', max_length=32)),
                ('driver_name', models.CharField(blank=True, max_length=255)),
                ('driver_phone', models.CharField(blank=True, max_length=32)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
